import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Jamstack site with next.js, Tailwindcss and Fuse.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-sm font-bold underline">
      Hello world!
    </h1>
    </div>
  )
}
